{% set name = "numba4jax" %}
{% set version = "0.0.10.post1" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numba4jax-{{ version }}.tar.gz
  sha256: 887b71811fd0f35eec3d0217267fdc9d919bf252783ec9de5d53ffd4420c0350

build:
  number: 0
  noarch: python
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - cffi >=1.12
    - jax >0.2.16
    - jaxlib >0.1.70
    - numba >=0.52.0,!=0.54.0
    - numpy ~=1.18
    - python >=3.7

test:
  imports:
    - numba4jax
  # not active right now because the recipe has less restrictive pins
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: http://github.com/PhilipVinc/numba4jax
  summary: Usa numba in jax-compiled kernels.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - PhilipVinc
